Usage:
  snabb lgs set  <key> <value>
  snabb lgs get  <key>　[--all]
  snabb lgs list <key>
  snabb lgs add  <key> <value>
  snabb lgs del  <key> [pos]
  snabb lgs pkg_install <pkg_name>
  snabb lgs pkg_list
  snabb lgs pkg_uninstall <pkg_name>
  snabb lgs split <stream_name> [filename]
  snabb lgs extract <stream_name> [filename] [--rule <rule_name>] [--sample <N>]
  snabb lgs auth -u <user_name> [-h <host>]
  snabb lgs run　[-c conf_path] [--key key_file] [--host <host>]


Use --help for per-command usage. Example:

  snabb lgs run --help
